### ISSUE TITLE
Issue with run-meteor-on-google-app-engine

### ISSUE THREAD

**Issue by ffxsam** [GoogleCloudPlatform/community#146]
This document is out of date and doesn't work with Meteor 1.4. Would be great to see this updated.

```
> meteor-dev-bundle@0.0.0 install /app/programs/server
> node npm-rebuild.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "install" "--unsafe-perm"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/programs/server/npm-debug.log
The command '/bin/sh -c (cd programs/server && npm install --unsafe-perm)' returned a non-zero code: 1
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:85504a905a1f680ce0efead225cc36aec0655561b34dcaf7ce3dea96d917f44d" failed: exit status 1

ERROR: (gcloud.app.deploy) Error Response: [2] Build failed; check build logs for details
```

**Comment by jmdobry** [comment]
@ffxsam Thanks for letting us know, do you have any interest or knowledge on how it should be updated?

**Comment by ffxsam** [comment]
Not yet. Honestly I'm not even experience enough with GCP or Docker to know what's going wrong here. How can I edit this tutorial if/when I do come up with a solution?

**Comment by jmdobry** [comment]
https://github.com/GoogleCloudPlatform/community/edit/master/tutorials/run-meteor-on-google-app-engine.md

**Comment by felipecaldas** [comment]
Does not work, I am afraid @jmdobry 

Here's my error log:

```
tep 2/4 : COPY . /app/
 ---> 4f7d300b8c65
Removing intermediate container f7c74bac3853
Step 3/4 : RUN (cd programs/server && npm install --unsafe-perm)
 ---> Running in cdd1e039e88c

> fibers@1.0.15 install /app/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-48` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /app/programs/server
> node npm-rebuild.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "install" "--unsafe-perm"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/programs/server/npm-debug.log
The command '/bin/sh -c (cd programs/server && npm install --unsafe-perm)' returned a non-zero code: 1
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:c932178fff700a08f3f889809a7d48561268d4d91c061db914d8fdcb650ab998" failed: exit status 1

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.app.deploy) Cloud build failed. Check logs at https://console.cloud.google.com/gcr/builds/e36a98ad-1b93-45af-90c9-552b2a1925ad?project=arbbot-181022 Failure status: UNKNOWN: Error Response: [2] Build failed; check build logs for details

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! arbmatrix@ deploy: `npm run predeploy && (cd ../bundle && gcloud app deploy -q)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the arbmatrix@ deploy script 'npm run predeploy && (cd ../bundle && gcloud app deploy -q)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the arbmatrix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run predeploy && (cd ../bundle && gcloud app deploy -q)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs arbmatrix
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls arbmatrix
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fcaldas/projects/meteor/arbmatrix/npm-debug.log
```

**Comment by jmdobry** [comment]
fyi @ace-n

**Comment by bgadrian** [comment]
Same error occured to me today, no fix yet. 

Their meteor tutorial is not up-to-date, the generate config command is deprecated I had to build the yaml from their docs. 

Because NPM is a ..sh. software it does not generate a friendly error so I don't know what is wrong, the log is generally 
```bash
Error: spawn npm ENOENT
at _errnoException (util.js:992:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
at Function.Module.runMain (module.js:695:11)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
```

**Comment by ToddKopriva** [comment]
@ace-n , can you have a look at this issue report regarding a tutorial that you contributed?

**Comment by ToddKopriva** [comment]
This tutorial has been archived:
#1014
