### ISSUE TITLE
tutorials/dlp-to-datacatalog-tags script does not work for tables that require filter on partition field

### ISSUE THREAD

**Issue by wsjk** [GoogleCloudPlatform/community#1622]
When executing final script in tutorial, I get errors trying to use a DLP template to tag a table with a partition field filter requirement.

Example error message:

```
+java.sql.SQLException: [Simba][BigQueryJDBCDriver](100033) Error getting job status.
	at com.simba.googlebigquery.googlebigquery.client.BQClient$2.throwException(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient$RequestWithRetry.executeWithRetry(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeQuery(Unknown Source)
	at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:291)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100033) Error getting job status.
	... 13 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "Cannot query over table 'dataset.table_name' without a filter over column(s) 'time' that can be used for partition elimination",
    "reason" : "invalidQuery"
  } ],
  "message" : "Cannot query over table 'dataset.table_name' without a filter over column(s) 'time' that can be used for partition elimination",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1092)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.simba.googlebigquery.googlebigquery.client.BQClient$2.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient$RequestWithRetry.executeWithRetry(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeQuery(Unknown Source)
	at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:291)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by ToddKopriva** [comment]
@imadethis and @mesmacosta , can you have a look at this issue regarding a document that you contributed?

**Comment by mesmacosta** [comment]
I will take a look at this.

**Comment by mesmacosta** [comment]
Hi @wsjk thanks for reporting the issue.

The tutorial did not support BigQuery tables with required partition filters, I've updated the tutorial code with a fix to handle such scenario.

Could you verify if the fix solves your issue, by executing the tutorial at:
https://github.com/mesmacosta/community/blob/fix/handle-required-partition-filter/tutorials/dlp-to-datacatalog-tags ?

If so, I will submit a PR with this fix to the community repo. @imadethis feel free to review the code and suggest changes.

**Comment by ToddKopriva** [comment]
Thanks, @mesmacosta .

**Comment by wsjk** [comment]
Hi @mesmacosta ,

I'm still getting an error when I run following command 

```
java -cp target/dlp-to-datacatalog-tags-0.1-jar-with-dependencies.jar com.example.dlp.DlpDataCatalogTagsTutorial \
-dbType "bigquery" \
-projectId xxxxx \
-minThreshold 100 \
-limitMax 1000 \
-dbName xxxxx \
-threadPoolSize 5 \
-tableName xxxxx \
-inspectTemplate xxxxx
```

Full traceback
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Start: Thu Mar 11 08:00:46 MST 2021]
Inspect SQL via JDBC V0.1
jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=xxxxxx;
-----------------------------------------
 Start Run ID: 06632b72-2680-407e-9898-55f0b23a2d63
-----------------------------------------
|
> DLP infoType Profile: [Cordial][contact_activity]java.sql.SQLException: [Simba][BigQueryJDBCDriver](100033) Error getting job status.
	at com.simba.googlebigquery.googlebigquery.client.BQClient$2.throwException(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient$RequestWithRetry.executeWithRetry(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeQuery(Unknown Source)
	at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:291)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100033) Error getting job status.
	... 13 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "Cannot query over table 'xxxxxx' without a filter over column(s) 'time' that can be used for partition elimination",
    "reason" : "invalidQuery"
  } ],
  "message" : "Cannot query over table 'Cordial.contact_activity' without a filter over column(s) 'time' that can be used for partition elimination",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1092)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.simba.googlebigquery.googlebigquery.client.BQClient$2.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient$RequestWithRetry.executeWithRetry(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.executeQuery(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.dataengine.BQSQLExecutor.execute(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SStatement.executeQuery(Unknown Source)
	at com.example.dlp.DlpDataCatalogTagsTutorial.lambda$processTable$1(DlpDataCatalogTagsTutorial.java:291)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

-----------------------------------------
 1 tables inspected
 End Run ID: 06632b72-2680-407e-9898-55f0b23a2d63
-----------------------------------------
[End: Thu Mar 11 08:01:52 MST 2021]
[Duration:   0 days,   0 hours,   1 minutes,   6 seconds.]
```

**Comment by mesmacosta** [comment]
Hi @wsjk,

The fix is not merged yet to this repo, did you test at https://github.com/mesmacosta/community/blob/fix/handle-required-partition-filter/tutorials/dlp-to-datacatalog-tags?

**Comment by wsjk** [comment]
@mesmacosta ah my bad. Initially cloned your fork but didn't use correct branch

So just to double check:
`origin	git@github.com:mesmacosta/community.git (fetch)`
`* fix/handle-required-partition-filter bb49be4 FIX add method to handle required partition filters`

![image](https://user-images.githubusercontent.com/16106458/110818849-e2407d00-824a-11eb-98a6-ea9737543d97.png)

Running same cmd I mentioned earlier and still getting exact same error

**Comment by mesmacosta** [comment]
Just to make sure,

did you clean the project again, before running `target/dlp-to-datacatalog-tags-0.1-jar-with-dependencies.jar` ?

**Comment by wsjk** [comment]
@mesmacosta ah yes cleared everything out and restarted from scratch **and it worked!**

Thank you!

output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Start: Thu Mar 11 10:07:04 MST 2021]
Inspect SQL via JDBC V0.1
jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=xxxxxxx;
-----------------------------------------
 Start Run ID: 4a8e9405-f179-42a4-8d1d-fb1dcf13f4a8
-----------------------------------------
|
> DLP infoType Profile: [xxxx][xxxxx].....+...+...............
-----------------------------------------
 1 tables inspected
 End Run ID: 4a8e9405-f179-42a4-8d1d-fb1dcf13f4a8
-----------------------------------------
[End: Thu Mar 11 10:08:28 MST 2021]
[Duration:   0 days,   0 hours,   1 minutes,   24 seconds.]

```

**Comment by mesmacosta** [comment]
Nice! I will submit the PR to this repo, thanks for helping testing it out!
