### ISSUE TITLE
Cannot load JDBC driver class(jmeter-spanner-performance-test/index.md)

### ISSUE THREAD

**Issue by Jeevak2100** [GoogleCloudPlatform/community#2360]
Getting the below error when running the Job from command line.
Have provided the path of the downloaded jar in Jmereter, also tried adding the jar files in the lib.

https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/jmeter-spanner-performance-test/index.md

Error.
Cannot load JDBC driver class 'com.google.cloud.spanner.jdbc.JdbcDriver'
java.lang.ClassNotFoundException: com.google.cloud.spanner.jdbc.JdbcDriver
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:49)
        at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:459)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:525)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731)
        at org.apache.jmeter.protocol.jdbc.config.DataSourceElement$DataSourceComponentImpl.getConnection(DataSourceElement.java:362)
        at org.apache.jmeter.protocol.jdbc.config.DataSourceElement.getConnection(DataSourceElement.java:199)
        at org.apache.jmeter.protocol.jdbc.sampler.JDBCSampler.sample(JDBCSampler.java:80)
        at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
        at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by ToddKopriva** [comment]
@shashank-google , could you take a look at this issue about a document that you contributed?

**Comment by shashank-google** [comment]
Which java version, spanner driver version and jmeter version are you using?
Back when I wrote this, it was tested  on java 8 and jmeter 5.x

**Comment by Jeevak2100** [comment]
I am using the latest Java version: Java 19.0.2
Jmeter 5.5

**Comment by shashank-google** [comment]
Can you try with Java 8 and update if it works.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
