### ISSUE TITLE
Issue with run-laravel-on-appengine-flexible

### ISSUE THREAD

**Issue by mahkassem** [GoogleCloudPlatform/community#390]
I'm trying to upload Laravel 5.6 Project to app engine but I keep getting the following error:

**Google Cloud SDK info:**
`Beginning deployment of service [default]...
INFO: Need Dockerfile to be generated for runtime php
Building and pushing image for service [default]
INFO: Could not generate [source-context.json]: Could not list remote URLs from source directory: C:\Users\user\Desktop\project_dir
Stackdriver Debugger may not be configured or enabled on this application. See https://cloud.google.com/debugger/ for more information.
INFO: Ignoring file [.env]: File matches ignore regex.
INFO: Ignoring file [.env.example]: File matches ignore regex.
Some files were skipped. Pass `--verbosity=info` to see which ones.
You may also view the gcloud log file, found at
[C:\Users\user\AppData\Roaming\gcloud\logs\2018.03.18\16.32.06.605000.log].
INFO: Uploading [c:\users\user\appdata\local\temp\tmpm6ljnj\src.tgz] to [us.gcr.io/project_id/appengine/default.20180318t163208:latest]
INFO: Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x00000000091E94E0>]
INFO: Using runtime builder [gs://runtime-builders/php-default-builder-20180306131233.yaml]
INFO: Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x000000000D795080>]
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: unable to resolve source`

**Error Log File Content**
`2018-03-18 16:32:06,608 DEBUG    root            Loaded Command Group: ['gcloud', 'app']
2018-03-18 16:32:06,864 DEBUG    root            Loaded Command Group: ['gcloud', 'app', 'deploy']
2018-03-18 16:32:06,867 DEBUG    root            Running [gcloud.app.deploy] with arguments: [--verbosity: "info"]
2018-03-18 16:32:06,900 DEBUG    root            API endpoint: [https://appengine.googleapis.com/], API version: [v1]
2018-03-18 16:32:08,818 INFO     ___FILE_ONLY___ Services to deploy:

2018-03-18 16:32:08,819 INFO     ___FILE_ONLY___ descriptor:      [C:\Users\user\Desktop\project_idloud\app.yaml]
source:          [C:\Users\user\Desktop\project_idloud]
target project:  [project_id]
target service:  [default]
target version:  [20180318t163208]
target url:      [https://project_id.appspot.com]

2018-03-18 16:32:12,144 DEBUG    root            No bucket specified, retrieving default bucket.
2018-03-18 16:32:12,150 DEBUG    root            Using bucket [gs://staging.project_id.appspot.com].
2018-03-18 16:32:13,862 DEBUG    root            Service [appengineflex.googleapis.com] is already enabled for project [project_id]
2018-03-18 16:32:14,119 INFO     ___FILE_ONLY___ Beginning deployment of service [default]...

2018-03-18 16:32:14,122 INFO     root            Need Dockerfile to be generated for runtime php
2018-03-18 16:32:14,127 INFO     ___FILE_ONLY___ Building and pushing image for service [default]

2018-03-18 16:32:14,230 DEBUG    root            Could not call git with args ('config', '--get-regexp', 'remote\\.(.*)\\.url'): Command '['git', 'config', '--get-regexp', 'remote\\.(.*)\\.url']' returned non-zero exit status 1
2018-03-18 16:32:14,230 INFO     root            Could not generate [source-context.json]: Could not list remote URLs from source directory: C:\Users\user\Desktop\project_idloud
Stackdriver Debugger may not be configured or enabled on this application. See https://cloud.google.com/debugger/ for more information.
2018-03-18 16:32:16,621 INFO     root            Ignoring file [.env]: File matches ignore regex.
2018-03-18 16:32:16,622 INFO     root            Ignoring file [.env.example]: File matches ignore regex.
2018-03-18 16:32:19,015 INFO     ___FILE_ONLY___ Some files were skipped. Pass `--verbosity=info` to see which ones.

2018-03-18 16:32:19,016 INFO     ___FILE_ONLY___ You may also view the gcloud log file, found at
[C:\Users\user\AppData\Roaming\gcloud\logs\2018.03.18\16.32.06.605000.log].

2018-03-18 16:36:11,762 INFO     root            Uploading [c:\users\user\appdata\local\temp\tmpm6ljnj\src.tgz] to [us.gcr.io/project_id/appengine/default.20180318t163208:latest]
2018-03-18 16:51:00,793 DEBUG    root            Using runtime builder root [gs://runtime-builders/]
2018-03-18 16:51:00,795 DEBUG    root            Loading runtimes manifest from [gs://runtime-builders/runtimes.yaml]
2018-03-18 16:51:00,799 INFO     root            Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x00000000091E94E0>]
2018-03-18 16:51:02,690 DEBUG    root            Resolved runtime [php] as build configuration [gs://runtime-builders/php-default-builder-20180306131233.yaml]
2018-03-18 16:51:02,690 INFO     root            Using runtime builder [gs://runtime-builders/php-default-builder-20180306131233.yaml]
2018-03-18 16:51:02,743 INFO     root            Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x000000000D795080>]
2018-03-18 16:51:07,464 DEBUG    root            (gcloud.app.deploy) INVALID_ARGUMENT: unable to resolve source
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 797, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 757, in Run
    resources = command_instance.Run(args)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\surface\app\deploy.py", line 79, in Run
    parallel_build=False)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\command_lib\app\deploy_util.py", line 582, in RunDeploy
    flex_image_build_option=flex_image_build_option)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\command_lib\app\deploy_util.py", line 381, in Deploy
    flex_image_build_option)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\command_lib\app\deploy_util.py", line 275, in _PossiblyBuildAndPush
    self.deploy_options.parallel_build)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 443, in BuildAndPushDockerImage
    return _SubmitBuild(build, image, project, parallel_build)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 475, in _SubmitBuild
    build, project=project)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\cloudbuild\build.py", line 143, in ExecuteCloudBuild
    build_op = self.ExecuteCloudBuildAsync(build, project)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\cloudbuild\build.py", line 127, in ExecuteCloudBuildAsync
    build=build,))
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\third_party\apis\cloudbuild\v1\cloudbuild_v1_client.py", line 204, in Create
    config, request, global_params=global_params)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\lib\third_party\apitools\base\py\base_api.py", line 722, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\lib\third_party\apitools\base\py\base_api.py", line 728, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "C:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\..\lib\third_party\apitools\base\py\base_api.py", line 599, in __ProcessHttpResponse
    http_response, method_config=method_config, request=request)
HttpBadRequestError: HttpError accessing <https://cloudbuild.googleapis.com/v1/projects/project_id/builds?alt=json>: response: <{'status': '400', 'content-length': '114', 'x-xss-protection': '1; mode=block', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Sun, 18 Mar 2018 14:51:08 GMT', 'x-frame-options': 'SAMEORIGIN', 'alt-svc': 'hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="41,39,35"', 'content-type': 'application/json; charset=UTF-8'}>, content <{
  "error": {
    "code": 400,
    "message": "unable to resolve source",
    "status": "INVALID_ARGUMENT"
  }
}
>
2018-03-18 16:51:07,467 ERROR    root            (gcloud.app.deploy) INVALID_ARGUMENT: unable to resolve source
2018-03-18 16:51:07,588 DEBUG    root            Metrics reporting process started...`

**System Configuration:**
OS: Windows 10 Pro | Version: 1709 | OS Build 16299.309

**Git**
`git version 2.15.1.windows.2`

**Laravel:**
5.6

**app.yaml**
`runtime: php
env: flex

runtime_config:
  document_root: public

skip_files:
  .env

env_variables:
  APP_LOG: errorlog
  APP_KEY: NEW_GENERATED_APP_KEY
  STORAGE_DIR: /tmp`

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
