### ISSUE TITLE
Issue deploying my spring boot app to Google App engine

### ISSUE THREAD

**Issue by vijayakumar-psg587** [GoogleCloudPlatform/community#557]
I've been trying to get the springboot app deployed to my app engine. There seems to be an issue while using the gcloud-maven-plugin version -2.0.9.133.v201611104
I used the command `mvn gcloud:run` but I always end up with the below error

 ```
Beginning interaction for module default...
0% Scanning for jsp files.
2018-10-04 12:50:39.631:INFO::main: Logging initialized @389ms
2018-10-04 12:50:43.937:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.q.QuickStartWebApp@4f80542f{/,[file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/, jar:file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/lib/springfox-swagger-ui-2.7.0.jar!/META-INF/resources],STARTING}
MultiException[java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class from jar file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/lib/log4j-api-2.10.0.jar, java.lang.RuntimeException: Error scanning entry META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class from jar file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/lib/log4j-api-2.10.0.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/lib/log4j-api-2.10.0.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/lib/asm-commons-6.0.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/lib/asm-6.0.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/lib/asm-tree-6.0.jar]
	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:536)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:447)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:479)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1337)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.quickstart.QuickStartWebApp.doStart(QuickStartWebApp.java:165)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.appengine.tools.development.jetty9.QuickStartGenerator.generate(QuickStartGenerator.java:68)
	at com.google.appengine.tools.development.jetty9.QuickStartGenerator.main(QuickStartGenerator.java:47)
Failed to generate /Users/a1345875/Documents/bitbucket-code/target/appengine-staging/WEB-INF/quickstart-web.xml
```

I tried with JDK8 and as well as JDK 10 with their respective runtimes and libraries but each time I end up with the same error. 

This is my  app.yaml by the way

```
runtime: java
env: flex
threadsafe: true

handlers:
- url: /
  script: this field is required, but ignored

resources:
  memory_gb: 2.0
```

I also searched for answers in the web but all were pointing to the java runtime upgrade. I did that by upgrading from 8 . to 10 (since I am not able to find an open jdk 9 for mac installation ) but it did not help. Please provide me your suggestions

**Comment by vijayakumar-psg587** [comment]
Here is the pom.xml file 

      [](url)  https://github.com/vijayakumar-psg587/POMfile

**Comment by vijayakumar-psg587** [comment]
@JimTravis Thanks Jim. It worked after upgrading my asm.jar to a newer version

**Comment by ToddKopriva** [comment]
Vijay, based on your comment a few hours ago, I am going to close this issue.

The next time you have an issue with which you need help, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

The Issues section of this GitHub repository is not typically the best place to get such questions answered.
