### ISSUE TITLE
Deploying spring boot app on google app engine yelling with errors 

### ISSUE THREAD

**Issue by App-Teck** [GoogleCloudPlatform/community#878]
Hi, after following up the tutorial and successfully running my spring boot app on goole app engine by running:
`mvn spring-boot:run`
But i fail to deploy by running:
`mvn package appengine:deploy -e`

log error is : 
`   
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) argument --version/-v: Bad value [0.0.1-SNAPSHOT]: May only contain lowercase letters, digits, and hyphens. Must begin and end with a letter or digit. Must not exceed 63 characters.
[INFO] GCLOUD: Usage: gcloud app deploy [DEPLOYABLES ...] [optional flags]
[INFO] GCLOUD:   optional flags may be  --bucket | --help | --image-url | --promote |
[INFO] GCLOUD:                          --stop-previous-version | --version
[INFO] GCLOUD:
[INFO] GCLOUD: For detailed information on this command and its flags, run:
[INFO] GCLOUD:   gcloud app deploy --help
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  53.141 s
[INFO] Finished at: 2019-05-20T16:46:58+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:2.0.0:deploy (default-cli) on project ReviewContainer: App Engine application deployment failed: com.google.cloud.tools.appengine.operations.cloudsdk.process.ProcessHandlerException: com.google.cloud.tools.appengine.AppEngineException: Non zero exit: 2 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.google.cloud.tools.appengine.AppEngineException: Non zero exit: 2
    at com.google.cloud.tools.appengine.operations.cloudsdk.process.NonZeroExceptionExitListener.onExit (NonZeroExceptionExitListener.java:28)
    at com.google.cloud.tools.appengine.operations.cloudsdk.process.LegacyProcessHandler.syncRun (LegacyProcessHandler.java:144)
    at com.google.cloud.tools.appengine.operations.cloudsdk.process.LegacyProcessHandler.handleProcess (LegacyProcessHandler.java:83)
    at com.google.cloud.tools.appengine.operations.GcloudRunner.run (GcloudRunner.java:101)
    at com.google.cloud.tools.appengine.operations.Deployment.deploy (Deployment.java:86)
    at com.google.cloud.tools.maven.deploy.AppDeployer.deploy(AppDeployer.java:57)
    at com.google.cloud.tools.maven.deploy.DeployMojo.execute(DeployMojo.java:35)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debuglogging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get troubleshooting help.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by App-Teck** [comment]
i have fixed the problem by changing the deploy version name from 0.0.3-test to test-003-test. Thanks but now i have some run time error will discuss in the blog u sent. cheers

**Comment by ToddKopriva** [comment]
I'm glad that you got the naming issue sorted.
